In [2]:
from miditok import REMI, TokenizerConfig
from miditok.pytorch_data import DatasetMIDI
from symusic import Score
from torch.utils.data import DataLoader

/opt/anaconda3/envs/retro/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
config = TokenizerConfig(num_velocities=16, use_chords=True, use_programs=True)
tokenizer = REMI(config)
midi = Score("dataset/nesmdb/nesmdb_midi/nesmdb_midi/train/000_10_YardFight_00_01GameStart.mid")
tokens = tokenizer(midi)  # calling the tokenizer will automatically detect MIDIs, paths and tokens
# converted_back_midi = tokenizer(tokens)  # PyTorch, Tensorflow and Numpy tensors are supported
tokenizer["BOS_None"]

1

In [ ]:
from pathlib import Path
import tqdm
files_paths = list(Path("dataset").glob("**/*.mid"))
# it = tqdm(files_paths,desc="Tokenizing")
print(f"There are {len(files_paths)} mid files.")
tokenizer.train(vocab_size=30000, files_paths=files_paths)

There are 183839 mid files.


In [10]:
tokenizer.save("tokenizer.json")
tokenizer.from_pretrained("tokenizer.json")

In [42]:
from miditok.pytorch_data import DatasetMIDI,DataCollator
from torch.utils.data import DataLoader
dataset = DatasetMIDI(
    files_paths=files_paths,
    tokenizer=tokenizer,
    max_seq_len=2048,
    bos_token_id=tokenizer["BOS_None"],
    eos_token_id=tokenizer["EOS_None"],
)
# print(dataset[0].keys())

collator = DataCollator(tokenizer.pad_token_id,shift_labels=True)
dataloader = DataLoader(dataset, collate_fn=collator,batch_size=64)
first = next(iter(dataloader))
len(dataloader),first["input_ids"],first["attention_mask"],first["labels"]

(83,
 tensor([[    1,   788,  3797,  ...,     0,     0,     0],
         [    1,  1774,  1011,  ...,     0,     0,     0],
         [    1,  2979,  1607,  ...,     0,     0,     0],
         ...,
         [    1,  5657, 18121,  ...,     0,     0,     0],
         [    1,  1855, 15278,  ...,     0,     0,     0],
         [    1,  2095,  1168,  ...,     0,     0,     0]]),
 tensor([[1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0]], dtype=torch.int32),
 tensor([[    1,   788,  3797,  ...,  -100,  -100,  -100],
         [    1,  1774,  1011,  ...,  -100,  -100,  -100],
         [    1,  2979,  1607,  ...,  -100,  -100,  -100],
         ...,
         [    1,  5657, 18121,  ...,  -100,  -100,  -100],
         [    1,  1855, 15278,  ...,  -100,  -100,  -100],
         [    1,  2095,  1168,  ...,  -100,  -100,  -100]]))

In [46]:
import tqdm
for epoch in range(10):
    for batch in tqdm.tqdm(dataloader,desc=f"{epoch} Traning"):
        pass
        # print("ok")





0 Traning:   0%|          | 0/83 [00:00<?, ?it/s]



0 Traning:   1%|          | 1/83 [00:00<01:07,  1.21it/s]



0 Traning:   2%|▏         | 2/83 [00:01<00:57,  1.40it/s]



0 Traning:   4%|▎         | 3/83 [00:01<00:49,  1.62it/s]



0 Traning:   5%|▍         | 4/83 [00:02<00:47,  1.66it/s]



0 Traning:   6%|▌         | 5/83 [00:02<00:42,  1.82it/s]



0 Traning:   7%|▋         | 6/83 [00:03<00:42,  1.83it/s]



0 Traning:   8%|▊         | 7/83 [00:04<00:39,  1.91it/s]



0 Traning:  10%|▉         | 8/83 [00:04<00:35,  2.13it/s]



0 Traning:  11%|█         | 9/83 [00:04<00:33,  2.19it/s]



0 Traning:  12%|█▏        | 10/83 [00:05<00:32,  2.28it/s]



0 Traning:  13%|█▎        | 11/83 [00:05<00:30,  2.38it/s]



0 Traning:  14%|█▍        | 12/83 [00:06<00:30,  2.30it/s]



0 Traning:  16%|█▌        | 13/83 [00:06<00:33,  2.10it/s]



0 Traning:  17%|█▋        | 14/83 [00:07<00:37,  1.82it/s]



0 Traning:  18%|█▊        | 15/83 [00:07<00:36,  1.85it/s]



0 Traning:  19%|█▉    

KeyboardInterrupt: 